services:
  - type: web
    name: cakesbysurbhi
    runtime: static
    buildCommand: 'true'
    staticPublishPath: .
    autoDeployTrigger: commit
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: 'true'
